#ifndef MAIN_H
#define MAIN_H

#define STOPPED 1
#define RUNNING 2

/* include all the required system and standard libraries */
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <stdio_ext.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <unistd.h>
#include <signal.h>
#include <sys/wait.h>
 
/* Define commands types used by the shell */
#define BUILTIN		1
#define EXTERNAL	2
#define NO_COMMAND  3

/* structure for job's singly linked list */
typedef struct job
{
    pid_t pid;
    char command[100];
    int status;
    int job_no;
    struct job *link;
}Job;

extern Job *head;
extern char current_command[100];

/* Job list functions */ 
void insert_at_first(pid_t pid, char *command);
void print_jobs(void);
void print_jobs_reverse(Job *temp);
void delete_at_first(void);


/* Define ANSI color codes for formatted shell output */
#define ANSI_COLOR_RED     "\x1b[31m"
#define ANSI_COLOR_GREEN   "\x1b[32m"
#define ANSI_COLOR_YELLOW  "\x1b[33m"
#define ANSI_COLOR_BLUE    "\x1b[34m"
#define ANSI_COLOR_MAGENTA "\x1b[35m"
#define ANSI_COLOR_CYAN    "\x1b[36m"
#define ANSI_COLOR_RESET   "\x1b[0m"

extern char *external_commands[200];
extern char prompt[50];
extern pid_t pid;
extern int child_changed;
extern int current_job_no;
extern int previous_job_no;
extern int next_job_no ;
extern int exit_status;

void check_background_jobs(void);

/* Read a command from the user */
void scan_input(char *prompt, char *input_string);

/* Extract the command from the input string */
char *get_command(char *input_string);

/* Identify whether the command is built-in or external */
int check_command_type(char *command);

/* Handle echo command and special shell variable */
void echo(char *input_string, int status);

/* Execute built-in shell commands */
void execute_internal_commands(char *input_string);

/* Execute external commands */
void execute_external_commands(char *input_string);

/* execute n-pipe commands */
void execute_n_pipe(char *input_string);

/* Handle signals generated by the user */
void signal_handler(int sig_num);

/* Extract commands availavle as external executables */
void extract_external_commands(char **external_commands);

#endif