#include "main.h"

void scan_input(char *prompt, char *input_string)
{
    /* Check for completed background jobs before starting the shell */
    check_background_jobs();

    /* register handlers for terminal and child-process signals */
    signal(SIGINT, signal_handler);
    signal(SIGTSTP, signal_handler);
    signal(SIGCHLD, signal_handler);

    while(1)
    {
        if(child_changed)
        {
            check_background_jobs();
            child_changed = 0;
        }

        pid = 0; // shell is waiting for the input

        printf(ANSI_COLOR_BLUE "%s " ANSI_COLOR_RESET, prompt); //to print
        fflush(stdout);

        /* Read the command from the user */
        if(fgets(input_string, 100, stdin) == NULL)
        {
            clearerr(stdin);
            continue;
        }

        //remove new line generated by fgets
        input_string[strcspn(input_string, "\n")] = '\0';

        /*check whether the user wants to change the shell prompt */
        if(strncasecmp(input_string, "PS1=", 4) == 0)
        {
            /* Reject prompt values containing spaces */
            if(strchr(input_string, ' ') != NULL)
            {
                printf(ANSI_COLOR_RED "PS1 : Invalid Prompt Format\n" ANSI_COLOR_RESET);
            }
            /* if no space change the prompt */
            else
            {                                                                                       
                /* Update the shell prompt */
                strcpy(prompt, &input_string[4]);
                continue;
            }
        }        

        /* Extract the first command and identify its type */
        char *command = get_command(input_string);
        int ret = check_command_type(command);

        if(ret == BUILTIN)
        {
            execute_internal_commands(input_string);
        }
        else if(ret == EXTERNAL)
        {
            /* Check whether pipe is present */
            if(strchr(input_string, '|') != NULL)
            {
                execute_n_pipe(input_string);
            }
            else
            {
                /* Save the command for job-control operations */
                strcpy(current_command, input_string);

                execute_external_commands(input_string);       
            }     
        }
        else
        {
            printf(ANSI_COLOR_RED "%s: command not found\n" ANSI_COLOR_RESET, command);
            exit_status = 127;
        }
    }
}


char *get_command(char *input_string)
{
    /* Extract the first word of the input as the command */
    static char command[50];

    int i =0;

    while(input_string[i] != '\0' && input_string[i] != ' ' && input_string[i] != '\t' && input_string[i] != '|')
    {
        command[i] = input_string[i];
        i++;
    }

    command[i] = '\0';

    return command;
}

void signal_handler(int signum)
{
    if(signum == SIGINT)
    {
        /* Redisplay the prompt when Ctrl+C is pressed at the shell */
        if(pid == 0)
        {
            printf("\n");
            printf(ANSI_COLOR_BLUE "%s " ANSI_COLOR_RESET, prompt);
            fflush(stdout);
        }
    }
    else if(signum == SIGTSTP)
    {
        /* Ignore Ctrl+Z when the shell itself is waiting for input */
        if(pid == 0)
        {
            printf("\n");
            printf(ANSI_COLOR_BLUE "%s " ANSI_COLOR_RESET, prompt);
            fflush(stdout);
        }
        else
        {

            printf("\n");

            Job *temp = head;

            /* Find the stopped process in the job list */
            while(temp != NULL)
            {
                if(temp->pid == pid)
                {
                    temp->status = STOPPED;
                    return;
                }

                temp = temp->link;
            }
            /* Add a newly stopped process to the job list */
            insert_at_first(pid, current_command);
        }
    }
    else if(signum == SIGCHLD)
    {
         /* Notify the shell that a child process has changed state */
        child_changed = 1;
    }
}